module.exports = {
  NO_SHARE: 0,
  BLACKLISTED_UNTIL_NEXT_TERM: 1,
  VOTING_WINDOW_IS_NOT_CLOSED: 2,
  MASTER_STILL_COMMITTING: 3,
  CANDIDATE_OUTDATED_BY_TERM: 4,
  CANDIDATE_OUTDATED_BY_HISTORY: 5,
  CANDIDATE_HAS_WRONG_HISTORY: 6,
  ALREADY_VOTED: 7
};
